### ISSUE TITLE
[GNB](왼쪽 사이드바) UI

### ISSUE THREAD

**Issue by wngkfla01** [JoberChipFrappuccino/joberchip-fe#12]
# 기능
- 왼쪽 사이드메뉴바 UI
- 상단 아이콘 누르면 open/close되게
# 적용되는 페이지
- 전체 페이지 공통
# 추가 설명

# 예상 시작일
- 23.09.11
# 예상 완료일
- 23.09.13

**Comment by peacepiece7** [comment]
https://github.com/JoberChipFrappuccino/joberchip-fe/pull/17 다시 머지했습니다.
