### ISSUE TITLE
구글맵지도 사용자 편의성 개선

### ISSUE THREAD

**Issue by beakjiuk** [JoberChipFrappuccino/joberchip-fe#133]
<details>

지도 검색 수정할때 빈칸으로 나오게하기
수정, 추가시 (작은화면일때) 지도 검색후 상세주소를 바로 입력할수있게 자동으로 스크롤 내려주게 하기

<summary>Feature request rules</summary>

- 기본적으로 이슈를 작성하는 사람이 Assignee입니다.

- Labels로 진행 상황 표기합니다. (feature는 enhancement, bug는 bug 정도만 해주세요.)

- Assignees를 배정합니다.

- Branch는 `Feature/<이슈번호>-<기능>`으로 작성합니다.

- `JoberChipFrappuccinoFE` Project를 선택합니다.

</details>

# 기능

# 적용되는 페이지

# 추가 설명

# 예상 시작일

# 예상 완료일

**Comment by peacepiece7** [comment]
추적이 불가능하기 대문에 해당 이슈를 종료합니다.

이슈와 연결된 브런치를 꼭! 만들어서 작업해주세요.
